// Vercel — trả mentor.config.js (URL API qua ENV hoặc cùng domain)
export default function handler(req, res) {
  const custom = process.env.MENTOR_CHAT_PUBLIC_URL || "";
  const vercelUrl = process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}/api/mentor-chat`
    : "";
  const url = custom || vercelUrl || "";
  const safe = JSON.stringify(url);

  res.setHeader("Content-Type", "application/javascript; charset=utf-8");
  res.setHeader("Cache-Control", "public, max-age=0, s-maxage=300");
  res.status(200).send(
    "// Auto-generated by /api/mentor-config\n" +
      `window.__MENTOR_CHAT_URL__ = ${safe};\n`
  );
}
