// Vercel — trả mentor.config.js (không commit secret; URL API tuỳ chọn qua ENV)
export default function handler(req, res) {
  const custom = process.env.MENTOR_CHAT_PUBLIC_URL || "";
  const safe = JSON.stringify(custom);

  res.setHeader("Content-Type", "application/javascript; charset=utf-8");
  res.setHeader("Cache-Control", "public, max-age=0, s-maxage=300");
  res.status(200).send(
    "// Auto-generated by /api/mentor-config\n" +
      `window.__MENTOR_CHAT_URL__ = ${safe};\n`
  );
}
