// Vercel Serverless Function
// Trả về JS file set các biến __GOOGLE_TTS_*__ cho client.
//
// Logic mới:
//   • Endpoint /api/tts-google bây giờ TỰ FALLBACK sang Microsoft Edge TTS
//     (miễn phí, không cần key) khi Google không hoạt động.
//   • Vì vậy cờ __GOOGLE_TTS_USE_PROXY__ luôn = true → client luôn dùng
//     proxy server-side, không bao giờ rơi về Web Speech của trình duyệt
//     (vốn không có giọng vi-VN trên Android).
//
//   • Có thể đặt ENV TTS_FORCE_EDGE=1 để ép dùng Edge dù có Google key
//     (vd. khi thẻ bị khóa, không muốn tốn quota Google).

export default function handler(req, res) {
  const googleVoice = process.env.GOOGLE_TTS_VOICE || "vi-VN-Neural2-A";
  const safeVoice   = JSON.stringify(googleVoice);

  res.setHeader("Content-Type", "application/javascript; charset=utf-8");
  res.setHeader("Cache-Control", "public, max-age=0, s-maxage=300");

  res.status(200).send(
    `// Auto-generated by /api/tts-config - do not edit\n` +
    `window.__GOOGLE_TTS_API_KEY__   = "";\n` +
    `window.__GOOGLE_TTS_VOICE__     = ${safeVoice};\n` +
    `window.__GOOGLE_TTS_USE_PROXY__ = true;\n`
  );
}
