// Vercel Serverless Function
// Trả về JS file set các biến __GOOGLE_TTS_*__ cho client.
// Key thật KHÔNG xuống browser — chỉ bật cờ __GOOGLE_TTS_USE_PROXY__ để client
// gọi /api/tts-google (cũng đọc ENV trong server).
//
// URL production: /api/tts-config  (hoặc /secrets/tts.config.js qua rewrite trong vercel.json)

export default function handler(req, res) {
  const hasGoogle   = !!process.env.GOOGLE_TTS_API_KEY;
  const googleVoice = process.env.GOOGLE_TTS_VOICE || "vi-VN-Neural2-A";
  const safeVoice   = JSON.stringify(googleVoice);

  res.setHeader("Content-Type", "application/javascript; charset=utf-8");
  res.setHeader("Cache-Control", "public, max-age=0, s-maxage=300");

  res.status(200).send(
    `// Auto-generated by /api/tts-config - do not edit\n` +
    `window.__GOOGLE_TTS_API_KEY__   = "";\n` +
    `window.__GOOGLE_TTS_VOICE__     = ${safeVoice};\n` +
    `window.__GOOGLE_TTS_USE_PROXY__ = ${hasGoogle ? "true" : "false"};\n`
  );
}
