// Vercel Serverless Function
// Trả về JS file set window.__FPT_TTS_API_KEY__ và window.__FPT_TTS_VOICE__
// Key thật lấy từ Environment Variable trong Vercel Dashboard → không lộ trên GitHub.
//
// URL production: /api/tts-config  (hoặc /secrets/tts.config.js qua rewrite trong vercel.json)

export default function handler(req, res) {
  const key   = process.env.FPT_TTS_API_KEY   || "";
  const voice = process.env.FPT_TTS_VOICE     || "banmai";

  // Tránh bot chèn script lạ nếu key chưa cấu hình: chỉ output khi có key.
  const safeKey   = JSON.stringify(key);
  const safeVoice = JSON.stringify(voice);

  res.setHeader("Content-Type", "application/javascript; charset=utf-8");
  // Cache nhẹ tại CDN edge 5 phút; trình duyệt không cache để đổi key là ăn liền.
  res.setHeader("Cache-Control", "public, max-age=0, s-maxage=300");

  res.status(200).send(
    `// Auto-generated by /api/tts-config - do not edit\n` +
    `window.__FPT_TTS_API_KEY__ = ${safeKey};\n` +
    `window.__FPT_TTS_VOICE__   = ${safeVoice};\n`
  );
}
